### ISSUE TITLE
README の手順だけでは Module を作ることができない

### ISSUE THREAD

**Issue by champierre** [xcratch/xcx-example#1]
README の手順だけでは Module を作ることができませんでした。以下必要だったステップを列挙します。

- "Download scratch-gui on that location" のあとに、scratch-gui フォルダ以下で npm install を実行することが必要
- "node ./scripts/build.js ..." を実行しても、Error: Cannot find module 'fs-extra' というエラーが出て実行できなかった。事前に xcratch-example フォルダ以下で npm install を実行することが必要でした。
- mjs ファイルは *.github.io 以下で公開していないと読み込むことができませんでした。別ドメインで公開した mjs ファイルを読み込もうとすると CORS エラーとなります。

**Comment by yokobond** [comment]
ご指摘ありがとうございます。

README で適宜 `npm install` することを追加します。

「mjs ファイルは *.github.io 以下で公開していないと読み込むことができませんでした。」
この指摘については、読み込めない現象の解釈が違うように思います。
github.io のウェブサーバーは CORS を無制限で許可( `Access-Control-Allow-Origin: *` )しているので、ここに置いたモジュールファイルはどのサイトからも読み込めます。もし、モジュールファイルを CORS の許可をしていないサーバーに置くと別のドメインのサイトからは読み込めなくなります。
つまり、モジュールファイルを置いたウェブサーバーが github.io への CORS を許可していなかったということではないでしょうか?

**Comment by champierre** [comment]
はい、おそらく「モジュールファイルを置いたウェブサーバーが github.io への CORS を許可していなかった」なんだと思います。その方法を調べるのが面倒で僕はあきらめました。

**Comment by yokobond** [comment]
CORSは始めよくわからずに心配でしたが、github.io でしかモジュールを公開できないということではなくて良かったです。
公開方法についても README に書くようにします。

**Comment by yokobond** [comment]
READMEに開発環境構築やモジュールの公開方法とCORSについて追加しました。

9b71b90a7da6ada9bc8ee07a48aae0b7a86767f3
60d2372d4559171facae2f998916737a2bcf27a2
